---
title: "The Future is Female"
subtitle: "How German Female Local Politicians Prioritize the Future More Compared to Their Male Counterparts"
author: "Maurice Baudet von Gersdorff"
date: "2025-02-12"
date-format: long
format:
  revealjs:
    scrollable: false
    self-contained: false
    slide-number: true
    theme: default
bibliography: bibliography.bib
csl: hu-isw.csl
link-citations: true
execute:
  echo: true
---

## Introduction

**Academic Puzzle:**
Do politicians pursue policies with positive effects that only become apparent after their own current term of office?

**Research Question:**
How does a change in the gender composition of city and district councils in Germany affect the size of their budgets for long-term investments?

**Existing Literature:**
The allocation of funds by women is examined primarily in terms of policy areas and not in terms of short-term and long-term expenditure [@clayton_quota_2018; @funk_representative_2019].

---

## Argument

Women tend to prioritize the well-being of future generations more than men do due to their socialization [@gilligan_different_2003]. This is reflected in their higher priority on policies with long-term impact [@inglehart_rising_2003], which leads to increased long-term investments by city/district councils with more women.

---

## Hypotheses

1. An increase in the share of women in city and district councils leads to an increase in the budget size for long-term investments.

2. A decrease in the share of women in city and district councils leads to a decrease in the budget size for long-term investments.

---

## Research Design

**Regression Discontinuity Design (RDD)**

- “Research design for estimating a causal effect that estimates the discontinuous jump in an outcome on either side of a threshold that determines treatment assignment” [@bueno_de_mesquita_thinking_2021, 262]

- In this case: Estimating the causal effect of each additional woman on the council.

- Similar design to [@baskaran_women_2023], but different theoretical approach and outcome variable.

---

## Data Source

- Use of data from *Wegweiser Kommune* [@wegweiser_kommune_kommunale_2025] for information on the council's allocation of funds.

- Collect data by hand on the exact gender composition of the city/district councils. (*Wegweiser Kommune* provides only shares.)

---

## Limitations

- Limited to the German case due to data restrictions.

- Possible correlation between so-called female policy areas and long-term investments? → This can probably be controlled for using data on the allocation of funds per policy area.

- RDD requirements. → Refer to [@bueno_de_mesquita_thinking_2021, 243-265] for full discussion.

- Higher share of women probably correlates with the council's party composition. → GERDA dataset [@heddesheimer_german_2024] to control for confounders.

---

## References

::: {#refs}
:::